name: phizix
description: "Phizix - Flutter Application"
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.2
  shared_preferences: ^2.5.5
  get_it: ^9.2.1
  retrofit: ^4.9.2
  build_runner: ^2.13.1
  retrofit_generator: ^10.2.3
  json_annotation: ^4.11.0
  flutter_html: ^3.0.0
  firebase_core: ^4.6.0
  firebase_crashlytics: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true