# update_fastlane

default_platform(:android)

platform :android do

  desc "Run tests, build and distribute to Firebase"
  lane :test_and_distribute do

    # Unit tests
    sh("cd .. && flutter test test/ --reporter=compact")

    # Integration tests one by one
    sh("cd .. && flutter test integration_test/articles_flow_test.dart --reporter=compact")
    sh("cd .. && flutter test integration_test/app_flow_test.dart --reporter=compact")

    # Build release APK
    sh("cd .. && flutter build apk --release")

    # Distribute to Firebase App Distribution
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "testers",
      release_notes_file: "fastlane/release_notes.txt"
    )

  end

end